# Generated by Django 4.2.1 on 2023-05-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.DateField()),
                ('resulution', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=10)),
                ('rating', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('discription', models.TextField()),
                ('genere', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
